<?php

namespace AppBundle\Repository;

/**
 * ConfigfieldRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConfigfieldRepository extends \Doctrine\ORM\EntityRepository
{
}
