<?php

namespace AppBundle\Repository;

/**
 * ttr_formsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ttr_formsRepository extends \Doctrine\ORM\EntityRepository
{
}
