<?php

namespace AppBundle\Repository;

/**
 * ttrformSmbdextractRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ttrformSmbdextractRepository extends \Doctrine\ORM\EntityRepository
{
}
