<?php

namespace AppBundle\Repository;

/**
 * TtrfieldsfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtrfieldsfRepository extends \Doctrine\ORM\EntityRepository
{
}
