<?php

namespace AppBundle\Repository;

/**
 * TtrFormRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtrFormRepository extends \Doctrine\ORM\EntityRepository
{
}
