<?php

namespace AppBundle\Repository;

/**
 * TtrformRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TtrformRepository extends \Doctrine\ORM\EntityRepository
{
}
