<?php

namespace AppBundle\Repository;

/**
 * ValuesfRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ValuesfRepository extends \Doctrine\ORM\EntityRepository
{
}
